### ISSUE TITLE
The foxy ova file does not work with virtualbox

### ISSUE THREAD

**Issue by olmerg** [ros-industrial/industrial_training#347]
When I try to open the voa file in Virtualbox it does not open because is save  in SHA256 , possible solution:

- use vmware (change the instructions)
- convert the ova (https://kb.vmware.com/s/article/2151537)

**Comment by ljaniec** [comment]
Sidenote: Use of ovftool requires creating account on VMWare... Really annoying.

**Comment by JeremyZoss** [comment]
Sorry for the very slow response to this issue.  An easier fix for this issue is to remove the SHA256 check entirely.  Extract the ova contents using zip, delete the .mf file, then rezip the contents.  I have updated the internal instructions SwRI uses to generate these VM images to include this step.  The latest Foxy image (>=v3) should be updated and can be opened in VirtualBox.
